# Where things are
source:      .
destination: ./_site
plugins_dir: ./_plugins
layouts_dir: ./_layouts
data_dir: ./_data
includes_dir: ./_includes

#collections: null

# Handling Reading
safe:         false
include:      [".htaccess", "_pages"]
exclude:      ["doc", "Gemfile", "Gemfile.lock"]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
incremental: false

# Plugins
whitelist: []
gems:      []

# Conversion
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"
markdown:    kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
asciidoc: asciidoctor
asciidoc_ext: 'asciidoc,adoc,ad'

# Serving
detach:  false
port:    4000
host:    127.0.0.1
baseurl: "/github-project-name" # does not include hostname

# Outputting
permalink:     /blog/:year/:title.html
paginate: 10
paginate_path: /page:num
timezone: 'ES'

quiet:    false
defaults: []

asciidoctor:
  attributes:
    - hardbreaks!
    - source-highlighter=pygments
    - pygments-css=style

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  coderay:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
